apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple
  name: simple
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: simple
  type: NodePort